---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - name: Check if selinux is installed
      command: getenforce
      register: command_result
      ignore_errors: True

    - name: Install libselinux-python
      yum: name={{ item }}
      with_items:
        - epel-release
        - libselinux-python
      when: command_result|success and command_result.stdout != 'Disabled'

    - name: Permissive selinux
      selinux: state=disabled

    - name: Install gcc and rsync and git
      yum: name={{ item }}
      with_items:
        - gcc
        - rsync
        - git
