# Setup Zabbix Agent
- hosts: all
  sudo: yes
  roles:
     - role: dj-wasabi.zabbix-agent
       agent_server: 192.168.1.20
       agent_serveractive: 192.168.1.20
       zabbix_url: http://192.168.1.20
       agent_listeninterface: eth1
       agent_allowroot: 1

# Install zabbix-sender
- hosts: all
  sudo: yes
  tasks:
    - name: "RedHat | Installing zabbix-sender"
      yum:  pkg=zabbix-sender
            state=present
