# Setup Zabbix Agent
- hosts: all
  sudo: yes
  roles:
     - role: dj-wasabi.zabbix-agent
       agent_server: 192.168.1.20
       agent_serveractive: 192.168.1.20
       zabbix_url: http://192.168.1.20
       agent_listeninterface: eth1
#       zabbix_api_use: true
#       zabbix_api_user: Admin
#       zabbix_api_pass: zabbix
#       zabbix_create_host: present
#       zabbix_host_groups:
#         - Linux Servers
#       zabbix_link_templates:
#         - Template OS Linux
